### ISSUE TITLE
Cannot use await keyword in tags

### ISSUE THREAD

**Issue by fujiyama-pl** [riot/tag-loader#1]
I'm not able to use await keyword to invoke some async JS functions.
Tag-loader claims that 'await' is a reserved word.

For example: 

this.onClick = (e) => {
{
      let data=await getSomeData();
}

I was using webpack example as a playground.
https://github.com/riot/examples/tree/gh-pages/webpack

**Comment by GianlucaGuarini** [comment]
the async await keywords should be supported. Please try again with the newest riot release
