### ISSUE TITLE
Hot reload in Webpack broken on >1.0.0

### ISSUE THREAD

**Issue by laznic** [riot/tag-loader#15]
Not sure if this is an issue with [riot-hot-reload](https://github.com/riot/hot-reload) instead, but posting here since this problem arose when updating riot-tag-loader. Let me know if you'd like me to open this issue in the hot-reload repo instead.

1. Describe your issue:  Whenever there is a change made in a `.tag` file, Webpack does compile the change, but the hot reload isn't applied to the component. The change is visible only after a manual page refresh. Hot reloading works fine in regular `.js` files.

2. Can you reproduce the issue? Yes, even the [Webpack example](https://github.com/riot/examples/tree/gh-pages/webpack) is broken. Steps to reproduce below.
    - Clone or download the example repo
    - Go to the Webpack directory
    - Run `npm install -D riot-compiler` (since the compiler seems to be missing)
    - Go to `localhost:3000` or `localhost:3000/webpack-dev-server` to see that the app is running
    - Change, e.g. the `Generate` button text to something else in `random.tag`
    - Go back to `localhost:3000`
    - Nothing changed, but in console there are logs about HMR happening

3. On which browser/OS does the issue appear? macOS Sierra, Chrome 63

4. Which version of Riot does it affect? >=3.7.4

5. How would you tag this issue?
- [ ] Question
- [x] Bug
- [ ] Discussion
- [ ] Feature request
- [ ] Tip
- [ ] Enhancement
- [ ] Performance

**Comment by GianlucaGuarini** [comment]
fixed thank you!
