### ISSUE TITLE
Cannot disable source maps

### ISSUE THREAD

**Issue by tototoben** [riot/tag-loader#21]
I'd like to disable source maps, but that doesn't seem possible via tag loader options due to the following line:
https://github.com/riot/tag-loader/blob/master/index.js#L48

Would be great to have that be configurable for the loader because right now the source maps are not very useful (they don't correctly map).

Forked with the following commit for now:
https://github.com/tototoben/tag-loader/commit/79935fb9b3214895a80ee8329edf58787ab4f6f0

**Comment by GianlucaGuarini** [comment]
could you please make a PR adding also a simple test for it? thank you

**Comment by GianlucaGuarini** [comment]
fixed in riot-tag-loader@2.1.0 thank you
