### ISSUE TITLE
Including riot with script tag and using tag loader produces error

### ISSUE THREAD

**Issue by amorygalili** [riot/tag-loader#23]
I'm writing a riot app that requires me to use the tag loader inside webpack and include riot using a <script> tag:

**/src/index.html**
```html
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/riot@3.13/riot.min.js"></script>
  </head>
  <body>
  </body>
</html>
```

**/src/a.js**
```javascript
import './test.tag';
```

**/src/b.js**
```javascript
import './test.tag';
```

**/src/test.tag**
```html
<test>
  <p>Test tag</p>
</test>
```

**webpack.config.js**
```javascript
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');

module.exports = {
  context: path.resolve(__dirname, "src"),
  entry: {
    'a': './a.js',
    'b': './b.js'
  },
  output: {
    filename: "[name].bundle.js",
    path: path.resolve(__dirname, 'dist')
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        include: /src/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader"
        }
      },
      {
        test: /\.tag$/,
        exclude: /node_modules/,
        use: [{
          loader: 'riot-tag-loader'
        }],
      }
    ]
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: 'index.html'
    })
  ],
  devServer: {
    open: true,
    port: 12000
  },
};
```

In chrome I get this error when I try to run this app:

_Uncaught TypeError: Cannot redefine property: brackets_

![screen shot 2018-11-18 at 5 56 14 pm](https://user-images.githubusercontent.com/6786620/48679208-4c552580-eb5b-11e8-90d3-96aea06bbc2f.png)

![screen shot 2018-11-18 at 5 57 26 pm](https://user-images.githubusercontent.com/6786620/48679215-7870a680-eb5b-11e8-992c-8d48a1992f8c.png)

I need to include riot in a <script> tag because the app needs to be extensible and you should be able to build extensions as .js files outside of webpack. I would like the API of the app to be available to these extensions through the global scope (window), which includes access to riot.

**Comment by GianlucaGuarini** [comment]
You don't need to include riot via `<script>` if you are using webpack, it will be automatically loaded into your bundle.

**Comment by amorygalili** [comment]
Yes, but for my app I need it so users can create extensions that aren't built with webpack, so they need to have riot available in the global scope.

**Comment by GianlucaGuarini** [comment]
so just add this to your webpack configuration:
```
 externals: {
    riot: 'riot'
  }
```

**Comment by amorygalili** [comment]
Thank you! That fixed all my problems.
