### ISSUE TITLE
Deprecation Warning: loaderUtils.parseQuery()

### ISSUE THREAD

**Issue by mattburton** [riot/tag-loader#3]
Just getting around to upgrading from Riot 2.x and Webpack 1.x and switching from riotjs-loader to the official one. I'm getting this warning during builds now:

> loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

Everything is working fine despite the warning - thought I'd let you guys know just in case.

**Comment by mashpie** [comment]
+1 - would love to see an update on this

**Comment by racquetmaster** [comment]
+1
