### ISSUE TITLE
using require inside a riot tag

### ISSUE THREAD

**Issue by sowhatdoido** [riot/tag-loader#6]
I'm trying to load an image like so:

```
<foo-bar>
   <img src="{require('./image.jpg')}" />
</foo-bar>
```

but an error is thrown: 

```
foo.bundle.js:1249 TypeError: (intermediate value)(intermediate value)(intermediate value).require is not a function
    at Tag$1.eval (eval at _create (foo.bundle.js:1258), <anonymous>:3:43)
    at _tmpl (foo.bundle.js:1222)
    at Tag$1.updateExpression (foo.bundle.js:1807)
    at each (foo.bundle.js:1561)
    at Tag$1.updateAllExpressions (foo.bundle.js:1893)
    at Tag$1.tagUpdate (foo.bundle.js:2772)
    at Tag$1.tagMount (foo.bundle.js:2879)
    at Object.updateExpression (foo.bundle.js:1796)
    at each (foo.bundle.js:1561)
    at Object.updateAllExpressions (foo.bundle.js:1893)
_logErr	@	foo.bundle.js:1249
```

Note that if I assign the require to a variable outside the tag then use said variable, everything works as expected. The problem is that I don't think we should have to create a variable per image asset just to load it into the tag. Anyone have a workaround for this?

**Comment by chrisdothtml** [comment]
I'm guessing what's happening is the webpack build is adding a variable reference to the imported image; e.g.

```
var some_import_reference = require('some_import_reference')

<foo-bar>
   <img src="{some_import_reference}" />
</foo-bar>
```

and when Riot tries to compile that, it's not finding `some_import_reference` in your tag's scope (it will look for `this.some_import_reference`).

To test my theory, you could instead try something like this:

```
<foo-bar>
   <img src="{image}" />

  <script>
    this.image = require('./image.jpg')
  </script>
</foo-bar>
```

**Comment by sowhatdoido** [comment]
I've tried that and I know it works but I wanted to prevent having to assign images to a variable if I could use it directly inline. I ended up creating a this.images array and requiring a bunch of images there but I was wondering if there was an elegant inline solution.

**Comment by GianlucaGuarini** [comment]
the riot template engine doesn't allow require calls. Use your require calls in your logic keeping your templates clean like @chrisdothtml has clearly demonstrated it.

There is nothing elegant in making `<img src={require('path/to/image')} />` 
good luck
