### ISSUE TITLE
Doesn't support a CSP build

### ISSUE THREAD

**Issue by Acesmndr** [riot/tag-loader#8]
I am building an extension for **chrome browser** and for automating the build process I was thinking of using the loader with **webpack**, It works fine but uses the default riot.js file for creating the bundle thus giving me **CSP issues** in the browser while loading the extension. I think we need some **option** or **query** to be passed to the loader such that the `riot.csp.js` would be used instead of `riot.js` while building the bundle.

**Comment by GianlucaGuarini** [comment]
see https://github.com/riot/tag-loader/pull/10#issuecomment-353861620
