### ISSUE TITLE
Accessing riot object inside tag

### ISSUE THREAD

**Issue by zorgoz** [riot/tag-loader#9]
Hello,

What is the (proper) way to make `riot` object accessible _**inside**_ `<script>` part of the tag file?
![image](https://user-images.githubusercontent.com/1569170/30282374-6aef7d38-9715-11e7-9a2c-afa1fdb13900.png)

(The same question applies for the router object.)

Thank you.

**Comment by GianlucaGuarini** [comment]
i think this issue is not related to the `tag-loader`. Could you please ask your question with a proper example in our main repo?
